name: 'Audio media type'
type: 'Dxpr Cms'
description: 'Adds a few enhancements to the audio file media type.'
recipes:
  - core/recipes/audio_media_type
install:
  - media_entity_download
  - media_file_delete
config:
  actions:
    media_file_delete.settings:
      simple_config_update:
        delete_file_default: true
    user.role.authenticated:
      grantPermission: 'download media'
