name: Case Studies
type: DXPR CMS
description: Adds a case study content type and listing page.
recipes:
  - dxpr_cms_page
  - core/recipes/content_editor_role
install:
  - link
  - add_content_by_bundle
  - menu_link_content
config:
  # Treat all field storages strictly, since they influence the database layout.
  strict:
    - field.storage.node.field_case_study__client_link
    - field.storage.node.field_case_study__client_logo
    - field.storage.node.field_case_study__client_name
  import:
  actions:
    user.role.content_editor:
      grantPermissions: []
    user.role.content_administrator:
      grantPermissions: []

    user.role.site_builder:
      grantPermissions: []
    workflows.workflow.basic_editorial:
      addNodeTypes: ['case_study']
