name: DXPR CMS
type: Site
description: Applies the foundational DXPR CMS recipes.
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - dxpr_cms_admin_ui
  - dxpr_cms_anti_spam
  - dxpr_cms_authentication
  - dxpr_cms_blog
  - dxpr_cms_page
  - dxpr_cms_privacy_basic
  - dxpr_cms_remote_video
  - dxpr_cms_seo_basic
  - dxpr_cms_basic_analytics
  - dxpr_cms_seo_tools
  - dxpr_cms_performance
  - dxpr_cms_dxpr_builder
  - dxpr_cms_dxpr_theme
  - dxpr_cms_roles
  - dxpr_cms_ai
  - dxpr_cms_ai_linkedin_posts
  - easy_email_express
install:
  - automated_cron
  - automatic_updates
  - block_classes
  - dashboard
  - eca_base
  - eca_config
  - eca_content
  - eca_misc
  - eca_render
  - eca_user
  - menu_link_content
  - package_manager
  - project_browser
  - update
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - menu_ui
  - token
  - views_ui
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    linkit:
      - image.style.linkit_result_thumbnail
    image:
      - image.style.large
      - image.style.thumbnail
    node:
      - views.view.content
    user:
      # This view mode is only needed because dxpr_theme expects it to exist
      # in certain situations.
      - core.entity_view_mode.user.compact
      - views.view.user_admin_people
  actions:
    package_manager.settings:
      simpleConfigUpdate:
        additional_trusted_composer_plugins:
          # This is indirectly added by `drupal/core-dev`.
          - tbachert/spi
    system.site:
      simpleConfigUpdate:
        name: 'DXPR CMS'
        page.front: '/home'
    system.theme:
      simpleConfigUpdate:
        default: dxpr_theme
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'access administration pages'
        - 'access content overview'
        - 'access contextual links'
        - 'access media overview'
        - 'administer url aliases'
        - 'create url aliases'
        - 'view own unpublished media'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view the administration theme'
        # Media management capabilities
        - 'create media'
        - 'delete media'
        - 'update media'
        - 'view media'
        - 'view all media revisions'
    user.role.content_administrator:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        # Managing media entities.
        - 'access media overview'
        - 'create media'
        - 'delete media'
        - 'update media'
        - 'view media'
        - 'view all media revisions'
        - 'view own unpublished media'
    user.role.site_builder:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'access media overview'
        - 'create media'
        - 'delete media'
        - 'update media'
        - 'view media'
        - 'view all media revisions'
        - 'view own unpublished media'
        - 'administer views'

    user.role.authenticated:
      grantPermissions:
        - 'delete own files'
        - 'view own unpublished content'
        - 'view welcome dashboard'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    # Enable the name field in the entity form so it can be modified.
    core.entity_form_display.media.document.*:
      setComponent:
        name: name
        options:
          type: string_textfield
          weight: -1
          region: content
    update.settings:
      simpleConfigUpdate:
        check.disabled_extensions: true
