name: 'Easy Email: Text Format'
description: 'Text format and editor config for editing HTML body of Easy Email templates.'
type: 'Easy Email'
install:
  - filter
  - editor
  - ckeditor5
config:
  actions:
    user.role.content_editor:
      grantPermissions:
        - 'use text format easy_email'
    user.role.content_administrator:
      grantPermissions:
        - 'use text format easy_email'
    user.role.site_builder:
      grantPermissions:
        - 'use text format easy_email'
