status:
  node:
    blog:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    case_study:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    drag_and_drop_page:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    event:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    news:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    page:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    person:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
    project:
      brand_voice_analyzer: true
      ai_sentiment_analyzer: true
