#!/usr/bin/env sh

## Description: Destroys and rebuilds the DDEV environment. This will delete and reinstall all dependencies.
## Usage: rebuild
## Example: "ddev rebuild"

ddev drush sql:drop -y
rm -r -f vendor $DDEV_DOCROOT composer.lock patches.lock.json
ddev restart
