name: 'DXPR CMS'
description: 'Applies all the DXPR CMS recipes.'
type: Site
recipes:
  - core/recipes/basic_block_type
  - core/recipes/core_recommended_performance
  - dxpr_cms_admin_theme
  - core/recipes/core_recommended_front_end_theme
  - core/recipes/user_picture
  # Not in Standard...
  - core/recipes/audio_media_type
  - core/recipes/document_media_type
  - core/recipes/local_video_media_type
  - core/recipes/remote_video_media_type
  - dxpr_cms_anti_spam
  - dxpr_cms_blog
  - dxpr_cms_basic_html_editor
  - dxpr_cms_dashboard
  - dxpr_cms_events
  - dxpr_cms_forms
  - dxpr_cms_full_html_editor
  - dxpr_cms_image_media_type
  - dxpr_cms_maintenance
  - dxpr_cms_media_tools
  - dxpr_cms_page_content_type
  - dxpr_cms_seo_basic
  - dxpr_cms_workflows
  - dxpr_builder_base
  - dxpr_builder_drag_and_drop_block
  - dxpr_builder_drag_and_drop_page
  - dxpr_theme_base
install:
  - bpmn_io
  - block_classes
  - config
  - contextual
  - datetime
  - eca_base
  - eca_misc
  - eca_user
  - field_ui
  - gin_login
  - help
  - history
  - inline_entity_form
  - inline_form_errors
  - login_emailusername
  - menu_link_content
  - menu_ui
  - moderation_dashboard
  - options
  - redirect
  - responsive_preview
  - section_library
  - shortcut
  - toolbar
  - trash
  - views_ui
  - xmlsitemap
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    trash: '*'
    image:
      - image.style.large
      - image.style.thumbnail
    node:
      - views.view.archive
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
      - views.view.glossary
    shortcut:
      - shortcut.set.default
    user:
      - core.entity_view_mode.user.compact
      - views.view.user_admin_people
      - views.view.who_s_new
      - views.view.who_s_online
  actions:
    node.type.blog:
      # Don't allow blog posts to have menu links by default, since that's
      # not normally what blog posts are for.
      setThirdPartySettings:
        -
          module: menu_ui
          key: available_menus
          value: []
        -
          module: menu_ui
          key: parent
          value: ''
    project_browser.admin_settings:
      simple_config_update:
        allowed_projects:
          recipes:
            - dxpr_cms_accessibility_tools
            - dxpr_cms_multilingual
            - dxpr_cms_seo_tools
    system.site:
      simple_config_update:
        name: 'DXPR CMS'
        page.front: '/node/9'
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissionsForEachNodeType:
        - 'clone %bundle content'
        - 'create %bundle content'
        - 'delete %bundle revisions'
        - 'delete any %bundle content'
        - 'edit any %bundle content'
      grantPermissionsForEachTaxonomyVocabulary:
        - 'create terms in %bundle'
        - 'edit terms in %bundle'
      grantPermissions:
        - 'access administration pages'
        - 'access block library'
        - 'access coffee'
        - 'access content overview'
        - 'access contextual links'
        - 'access media overview'
        - 'access navigation'
        - 'access site in maintenance mode'
        - 'access toolbar'
        - 'administer redirects'
        - 'administer url aliases'
        - 'create basic block content'
        - 'create url aliases'
        - 'edit any basic block content'
        - 'delete any basic block content'
        - 'delete own files'
        - 'revert all revisions'
        - 'use text format basic_html'
        - 'use text format full_html'
        - 'use text format restricted_html'
        - 'view all revisions'
        - 'view own unpublished media'
        - 'view the administration theme'
    views.view.files:
      disable: {}
    node.settings:
      simple_config_update:
        langcode: en
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'access help pages'
        - 'access shortcuts'
        - 'access user profiles'
        - 'delete own files'
        - 'view own unpublished content'
    user.role.anonymous:
      grantPermissions:
        - 'access content'
    user.settings:
      simple_config_update:
        verify_mail: true
        notify:
          cancel_confirm: true
          password_reset: true
          status_activated: true
          status_blocked: false
          status_canceled: false
          register_admin_created: true
          register_no_approval_required: true
          register_pending_approval: true
        register: visitors_admin_approval
        cancel_method: user_cancel_block
        password_reset_timeout: 86400
        password_strength: true
    moderation_dashboard.settings:
      simple_config_update:
        redirect_on_login: false
        chart_js_cdn: false
