name: DXPR Standard Roles
type: DXPR CMS
description: '@todo'
recipes:
  - core/recipes/content_editor_role
install:
  - user
  - node
  - system
  - block
config:
  strict: false
  import:
    user: '*'
