name: 'Full HTML editor'
type: 'DXPR CMS'
description: 'Enhances the Full HTML editor with better linking and media support.'
install:
  - ckeditor5
  - linkit
  - media_library
  - ai_ckeditor
config:
  import:
    linkit:
      - image.style.linkit_result_thumbnail
