name: 'Blog'
type: 'DXPR CMS'
description: 'Sets up a basic blog, with tagging and commenting.'
recipes:
  - dxpr_cms_content_type_base
  - dxpr_cms_basic_html_editor
  - dxpr_cms_image_media_type
  - core/recipes/tags_taxonomy
  - dxpr_builder_base
install:
  - dxpr_builder_page
  - dxpr_theme_helper
  - better_exposed_filters
  - menu_link_content
  - pathauto
config:
  # Treat all field storages strictly, since they influence the database layout.
  strict:
    - field.storage.node.field_content
    - field.storage.node.field_description
    - field.storage.node.field_image
    - field.storage.node.field_tags

