name: 'Blog'
type: 'DXPR CMS'
description: 'Sets up a basic blog, with tagging and commenting.'
recipes:
  - dxpr_cms_content_type_base
  - dxpr_cms_basic_html_editor
  - dxpr_cms_image_media_type
  - core/recipes/tags_taxonomy
install:
  - better_exposed_filters
  - menu_link_content
  - scheduler
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.blog:
          - basic
          - advanced
          - open_graph
