name: 'Admin Theme'
type: 'DXPR CMS'
description: 'Sets up a nice administrative theme and navigation.'
install:
  - coffee
  - gin
  - gin_toolbar
  - help
  - navigation
  - sam
  - type_tray
config:
  import:
    gin: '*'
    navigation: '*'
  actions:
    gin.settings:
      simple_config_update:
        enable_darkmode: auto
    system.theme:
      simple_config_update:
        admin: gin
