name: 'Recommended performance'
type: 'DXPR CMS'
description: 'Adds support for performance.'
install:
  - minifyhtml
  - speculative_loading
config:
  import:
    minifyhtml: '*'
    speculative_loading: '*'
  actions:
    system.performance:
      simple_config_update:
        _core:
          default_config_hash: jtno5biznHZbrIgKwzq-ze-7XaQxLCGe6PeUOR7bRiQ
        cache:
          page:
            max_age: 86400
    speculative_loading.settings:
      simple_config_update:
        mode: prerender
        eagerness: eager
