name: 'Recommended performance'
type: 'DXPR CMS'
description: 'Adds support for performance.'
install:
  - minifyhtml
config:
  import:
    minifyhtml: '*'
  actions:
    system.performance:
      simple_config_update:
        _core:
          default_config_hash: jtno5biznHZbrIgKwzq-ze-7XaQxLCGe6PeUOR7bRiQ
        cache:
          page:
            max_age: 86400
        stale_file_threshold: 172800
