services:
  php:
    image: tugboatqa/php:8.3-apache
    default: true
    depends:
      - db
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
      update:
        # Add the components as globally available path repositories, simulating Packagist.
        - find $TUGBOAT_ROOT -type d -maxdepth 1 -name 'dxpr_cms*' -exec composer config --global repositories.{} path {} ';'
        # Add the project template as a globally available path repository, simulating Packagist.
        - composer config --global repositories.template path $TUGBOAT_ROOT/project_template
        # Clean up from any previous build.
        - rm -Rf $TUGBOAT_ROOT/project
        # Create the project.
        - composer create-project drupal/dxpr-cms-project $TUGBOAT_ROOT/project --stability=dev
        # Symlink the Drupal root to the Apache web root.
        - ln -snf $TUGBOAT_ROOT/project/web $DOCROOT
        # Create the files directory and settings.php files with appropriate perms.
        - mkdir -p $DOCROOT/sites/default/files
        - chown -R www-data:www-data $DOCROOT/sites/default
        - chmod 2775 $DOCROOT/sites/default/files
        - cp $DOCROOT/sites/default/default.settings.php $DOCROOT/sites/default/settings.php
        # Disable PHP memory limit for Drush.
        - |
          echo "if (PHP_SAPI === 'cli') {
            ini_set('memory_limit', '-1');
          }" >> $DOCROOT/sites/default/settings.php
        # Install Drupal using Drush.
        - |
          set -e
          cd $TUGBOAT_ROOT/project
          vendor/bin/drush si \
            --yes \
            --db-url=mysql://tugboat:tugboat@db/tugboat \
            --account-pass=admin \
            --site-name="DXPR CMS Demo"
      build:
        # Run composer install and perform database updates
        - |
          set -e
          cd $TUGBOAT_ROOT/project
          composer install --optimize-autoloader
          vendor/bin/drush updatedb
          vendor/bin/drush cache:rebuild
        # Warm the caches
        - 'curl --silent -H "Host: $TUGBOAT_DEFAULT_SERVICE_URL_HOST" http://localhost > /dev/null'
  db:
    image: tugboatqa/mariadb
