name: Person Profiles
type: DXPR CMS
description: Adds a person profile content type.
recipes:
  - dxpr_cms_page
  - core/recipes/content_editor_role
install:
  - add_content_by_bundle
  - block_classes
  - dxpr_theme_helper
  - menu_link_content
  - smart_trim
  - telephone
  - views_bootstrap
config:
  strict:
    - field.storage.node.field_person__email
    - field.storage.node.field_person__phone_number
    - field.storage.node.field_person__role_job_title
  import:
    dxpr_theme_helper: '*'
  actions:
    user.role.content_editor:
      grantPermissions:
        - 'create person content'
        - 'delete person revisions'
        - 'delete own person content'
        - 'edit own person content'
        - 'view person revisions'
        - 'revert person revisions'
    user.role.content_administrator:
      grantPermissions:
        - 'create person content'
        - 'delete person revisions'
        - 'delete any person content'
        - 'edit any person content'
        - 'view person revisions'
        - 'revert person revisions'
    user.role.site_builder:
      grantPermissions:
        - 'create person content'
        - 'delete person revisions'
        - 'delete any person content'
        - 'edit any person content'
        - 'view person revisions'
        - 'revert person revisions'
    workflows.workflow.basic_editorial:
      addNodeTypes: ['person']
