name: News
type: DXPR CMS
description: Adds a news content type and listing page.
recipes:
  - dxpr_cms_page
  - core/recipes/content_editor_role
install:
  - add_content_by_bundle
  - menu_link_content
  - selective_better_exposed_filters
config:
  strict: false
  import:
    system:
      - system.menu.main
  actions:
    user.role.content_editor:
      grantPermissions:
        - 'create news content'
        - 'delete news revisions'
        - 'delete own news content'
        - 'edit own news content'
        - 'view news revisions'
        - 'revert news revisions'
    user.role.content_administrator:
      grantPermissions:
        - 'create news content'
        - 'delete news revisions'
        - 'delete any news content'
        - 'edit any news content'
        - 'view news revisions'
        - 'revert news revisions'

    user.role.site_builder:
      grantPermissions:
        - 'create news content'
        - 'delete news revisions'
        - 'delete any news content'
        - 'edit any news content'
        - 'view news revisions'
        - 'revert news revisions'
    workflows.workflow.basic_editorial:
      addNodeTypes: ['news']
