name: 'Multilingual support'
type: 'DXPR CMS'
description: 'Adds support for translations.'
recipes:
  - dxpr_cms_content_type_base
  - dxpr_cms_dxpr_builder
  - dxpr_cms_roles
install:
  - config_translation
  - content_translation
  - block_content
  - hreflang
  - language
  - node
  - tmgmt
  - tmgmt_google
  - tmgmt_locale
  - tmgmt_content
  - tmgmt_config
  - user
config:
  import:
    language: '*'
    tmgmt: '*'
  actions:
    'language.content_settings.node.%bundle':
      createIfNotExistsForEachNodeType:
        target_entity_type_id: node
        target_bundle: '%bundle'
        language_alterable: true
    language.content_settings.node.*:
      setThirdPartySettings:
        - module: content_translation
          key: enabled
          value: true
        - module: content_translation
          key: bundle_settings
          value:
            untranslatable_fields_hide: '1'
    user.role.content_administrator:
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'accept translation jobs'
        - 'create translation jobs'
        - 'submit translation jobs'
        - 'translate block_content'
        - 'translate editable entities'
        - 'translate menu_link_content'
        - 'translate tags taxonomy_term'
    user.role.content_editor:
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate editable entities'
        - 'translate tags taxonomy_term'
    user.role.marketer:
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate editable entities'
        - 'translate tags taxonomy_term'
    user.role.site_builder:
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'administer tmgmt'
        - 'accept translation jobs'
        - 'create translation jobs'
        - 'submit translation jobs'
        - 'delete translation jobs'
        - 'translate any entity'
        - 'translate block_content'
        - 'translate editable entities'
        - 'translate interface'
        - 'translate menu_link_content'
        - 'translate tags taxonomy_term'
        - 'administer tmgmt'
