name: 'Multilingual support'
type: 'Dxpr Cms'
description: 'Adds support for translations.'
install:
  - config_translation
  - content_translation
  - language
  - node
  - tmgmt
  - tmgmt_google
  - tmgmt_locale
  - tmgmt_content
  - tmgmt_config
config:
  import:
    language: '*'
    tmgmt: '*'
  actions:
    user.role.content_administrator:
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'accept translation jobs'
        - 'create translation jobs'
        - 'submit translation jobs'
        - 'translate block_content'
        - 'translate editable entities'
        - 'translate menu_link_content'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
    user.role.content_editor:
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate editable entities'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
    user.role.marketer:
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate editable entities'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
    user.role.site_bui:
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'administer tmgmt'
        - 'accept translation jobs'
        - 'create translation jobs'
        - 'submit translation jobs'
        - 'translate any entity'
        - 'translate block_content'
        - 'translate editable entities'
        - 'translate interface'
        - 'translate menu_link_content'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
