name: 'Dxpr Builder'
description: 'DXPR Builder visual layout builder.'
type: 'Builder'
recipes:
  - dxpr_builder_drag_and_drop_block
  - dxpr_builder_drag_and_drop_page
install:
  - entity_browser
  - dxpr_builder
  - dxpr_builder_media
  - options
  - field_group
config:
  import:
    entity_browser: '*'
    dxpr_builder: '*'
    dxpr_builder_media: '*'
  actions:
    system.site:
      simple_config_update:
        name: 'DXPR CMS'
        page.front: '/node/6'
    user.role.content_administrator:
      grantPermissions:
        - 'access dxpr_builder_media_modal entity browser pages'
        - 'edit with dxpr builder'
    user.role.content_editor:
      grantPermissions:
        - 'access dxpr_builder_media_modal entity browser pages'
        - 'edit with dxpr builder'
    user.role.marketer:
      grantPermissions:
        - 'access dxpr_builder_media_modal entity browser pages'
        - 'edit with dxpr builder'
    user.role.site_bui:
      grantPermissions:
        - 'access dxpr_builder_media_modal entity browser pages'
        - 'administer dxpr_builder_profile'
        - 'administer entity browsers'
        - 'edit with dxpr builder'
