name: 'Basic Page'
type: 'DXPR CMS'
description: 'Provides a basic Page content type with pretty URLs, moderation, scheduling, translation, and meta tags.'
recipes:
  - dxpr_cms_content_type_base
install:
  - pathauto
config:
  # We don't have strong opinions about the Page content type; this recipe exists
  # mainly for convenience.
  strict: false
