name: dxpr-cms-dev
type: drupal
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
hooks:
  post-start:
    # Copy the template project's `composer.json`, to build the code base.
    - exec: 'cp -f ./project_template/composer.json .'
    # Add the components as path repositories.
    - exec: "setup-repositories"
    # Install dependencies, and require any extra dev dependencies.
    - composer: 'require --dev drupal/default_content'
    # Copy PHPUnit configuration into the web root.
    - exec: 'cp -f phpunit.xml $DDEV_DOCROOT'
