name: dxpr-cms-dev
type: drupal
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
hooks:
  post-start:
    # Add the components as globally available path repositories.
    - exec: "refresh-components"
    # Symlink the template project's `composer.json` so any changes to it are reflected
    # in version control.
    - exec: 'ln -s -f ./project_template/composer.json'
    # Install dependencies.
    - composer: install
    # Copy PHPUnit configuration into the web root.
    - exec: 'cp -f phpunit.xml $DDEV_DOCROOT'
